PROGS_COUNTDOWN_OBJS := countdown.o
PROGS_COUNTDOWN_OBJS := $(PROGS_COUNTDOWN_OBJS:%=$(TDIR)/countdown/%)
ALL_OBJS += $(PROGS_COUNTDOWN_OBJS)

$(TDIR)/bin/countdown : $(TSTART) $(PROGS_COUNTDOWN_OBJS) $(TLIBC)

